name: build
# Trigger this workflow on pushes or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Set up Node.js (use the latest LTS version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
      # Step 4: Build the package
      - name: Build project
        run: npm run build
